[theme]
primaryColor="#F63366"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="sans serif"
OPENAI_API_KEY = "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"
